// utils/constants.js

export enum ErrorTypes {
    JOIN_LOBBY = "JOIN_LOBBY_ERROR",
    LEAVE_LOBBY = "LEAVE_LOBBY_ERROR",
    CREATE_LOBBY = "CREATE_LOBBY_ERROR",
    TOGGLE_READY = "TOGGLE_READY_ERROR",
    SEND_MESSAGE = "SEND_MESSAGE_ERROR",
    LIST_LOBBIES = "LIST_LOBBIES_ERROR",
    GET_LOBBY_INFO = "GET_LOBBY_INFO_ERROR",
    SET_NAME = "SET_NAME_ERROR",
    START_GAME = "START_GAME_ERROR",
}